appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: JDOEHiQdvBpHCLRK1gyuELdme5/wYAtP5Pn7OU1hoqp4igPt2piBNNAY0K7rpIrjpthul+JJp4e217Cl2w1FF/XNR1exj0sFXtg9NrKZZsdAvIJP1k41XuNkqgB6LGIuHFCueJynlFrDbKdNuLcjT93CBCpPS9nTkRajv+dl+By7hLlnQNjqV38UtgsskjBwYzLd3vp2mmxFU/SlFqZkNX15VK/uMuDP1i9mELyaHVLOtr24+iWJHU4cnbXjt8tVY1ZxPRrENHuGEsTdFyRYl2IVA/1X6ZMsoiKLupiT0HfaAPCfEXozSR+zmt9iipBO1wyOKH0May7Bs7d9S85wH9ltsFI7qLU78UVISmvLJduwbk6KVmpKL/87rE6prOZK6viYYZfCsGBuXvou8KGLqNUACuraweppUQIKhrrNeDBhYC0AFwAAmIpWZQNhT8m2NvI27LqL67gG0eCTBUuKypqGbfmnfkh/vJjguIRh5ipysJgnwpsCJhfXVQ9PxVtYHbOWCKhpotSt44Jhb2V+SvOE6W1xFes6ESc4gOpnwvt2YxCvYywEy9KcP3i48Q94oJJohSAcx/SCyltpKJgztOK5z5CFR5ou0ynggg0vAaRr/mZjAGEWYIeGS31pEi8WqoAiN5qHPk9huSZtZqdYcA6aPkmh1wEUjqfsf9S9at8=}
